using Game.Controllers.Initialize;
using Zenject;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by InstallerGenerator based on Entitas.InstallerGenerator2 by SmokyOoOwizard.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game
{
	public class ControllersInstaller : MonoInstaller
    {
		public override void InstallBindings()
        {
            var container = Container;
			Normal(container);
			Urgent(container);
            Container.BindInterfacesAndSelfTo<Bootstrap.Bootstrap>().AsSingle().NonLazy();
		}

		private void Normal(DiContainer container)
		{
		}

		private void Urgent(DiContainer container)
		{
			// 0001
			container.BindInterfacesAndSelfTo<InitializeController>().AsSingle();	// 0001
		}	
    }
}