using Test;
using Zenject;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by InstallerGenerator based on Entitas.InstallerGenerator2 by SmokyOoOwizard.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game
{
	public class SystemsInstaller : MonoInstaller
    {
		public override void InstallBindings()
        {
            var container = Container;
			Normal(container);
            Container.BindInterfacesAndSelfTo<Bootstrap.Bootstrap>().AsSingle().NonLazy();
		}

		private void Normal(DiContainer container)
		{
			// 0012
			container.BindInterfacesAndSelfTo<TestSystem>().AsSingle();	// 0012
		}	
    }
}